name: Codecov

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: cargo install cargo-kcov
    - name: Generate Coverage
      run: cargo kcov
    - uses: codecov/codecov-action@v2
